# Generated by Django 5.0.6 on 2024-06-04 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
