#!/bin/zsh


TOKEN=$(curl -s -X POST http://localhost:8000/api/user/login/ \
     -H "Content-Type: application/json" \
     -d '{"username": "testuser1", "password": "testpassword"}' \
     | jq -r '.access')

curl -X GET http://localhost:8000/api/session/join/377488/ \
     -H "Content-Type: application/json" \
     -H "Authorization: Bearer $TOKEN" \
    | cat >output.html