#!/bin/zsh
curl -s -X POST http://localhost:8000/api/user/register/ \
     -H "Content-Type: application/json" \
     -d '{"username": "testuser1", "password": "testpassword"}'

curl -s -X POST htt
     -H "Content-Type: application/json" \
     -d '{"refresh": "fjdasklfjlakf"}'

TOKEN=$(curl -s -X POST http://localhost:8000/api/user/login/ \
     -H "Content-Type: application/json" \
     -d '{"username": "testuser2", "password": "testpassword"}' \
     | jq -r '.access')


RESPONSE=$(curl -s -X POST http://localhost:8000/api/session/create/ \
     -H "Content-Type: application/json" \
     -H "Authorization: Bearer $TOKEN" \
     -d '{"draw_time": 30, "desc_time": 30}')

RESPONSE=$(curl -s -X PUT http://localhost:8000/api/session/360770/start/ \
     -H "Content-Type: application/json" \
     -H "Authorization: Bearer $TOKEN")


RESPONSE=$(curl -s -X POST http://localhost:8000/api/session/360770/wait/ \
     -H "Content-Type: application/json" \
     -H "Authorization: Bearer $TOKEN" \
     -d '{"game_code":360770,"draw_time":30,"desc_time":30,"created_at":"2024-06-07T00:43:50.922116Z","round":-1,"last_modified":"2024-06-07T00:52:01.893581Z","users":["testuser1","testuser2","testuser3"],"chains":[]}')

curl -s -X POST http://localhost:8000/api/session/360770/0/17/desc/ \
     -H "Content-Type: application/json" \
     -H "Authorization: Bearer $TOKEN" \
     -d '{"description": "test"}'

curl -s -X POST http://localhost:8000/api/session/145078/1/13/draw/ \
     -H "Content-Type: multipart/form-data" \
     -H "Authorization: Bearer $TOKEN" \
     -F "drawing=@/Users/anthonywu/Downloads/penguin.svg"

curl -s -X POST http://localhost:8000/api/session/435685/0/10/desc/ \
     -H "Content-Type: application/json" \
     -H "Authorization: Bearer $TOKEN" \
     -d '{"description": "test"}'

curl -s -X GET http://localhost:8000/api/session/145078/1/13/getDraw/ \
     -H "Authorization: Bearer $TOKEN" \

curl -s -X GET http://127.0.0.1:8000/media/13_145078_1.svg/ \
     -H "Content-Type: application/json" \
     -H "Authorization: Bearer $TOKEN" \

curl -s -X POST http://localhost:8000/api/session/435685/0/10/getDesc/ \
     -H "Content-Type: application/json" \
     -H "Authorization: Bearer $TOKEN" \
