# Generated by Django 5.0.6 on 2024-05-20 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='image',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='image',
            name='gameID',
            field=models.IntegerField(blank=True, default=0, max_length=6),
        ),
    ]
