# Generated by Django 5.0.6 on 2024-05-30 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_drawing_game_phrase_player_round_delete_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='drawing',
        ),
        migrations.RemoveField(
            model_name='phrase',
            name='suggested_by',
        ),
        migrations.RemoveField(
            model_name='round',
            name='game',
        ),
        migrations.CreateModel(
            name='Chain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chains', to='api.game')),
                ('starter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='started_chains', to='api.player')),
            ],
        ),
        migrations.CreateModel(
            name='DrawingPhrasePair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.CharField(max_length=255)),
                ('image', models.ImageField(null=True, upload_to='drawings/')),
                ('starter', models.BooleanField(default=False)),
                ('artist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drawings', to='api.player')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='api.player')),
                ('previous_pair', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_pair', to='api.drawingphrasepair')),
            ],
        ),
        migrations.DeleteModel(
            name='Drawing',
        ),
        migrations.DeleteModel(
            name='Phrase',
        ),
        migrations.DeleteModel(
            name='Round',
        ),
    ]
