# Generated by Django 5.0.6 on 2024-06-01 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_round_drawing_remove_phrase_suggested_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_id',
            field=models.IntegerField(default=0),
        ),
    ]
