# Generated by Django 5.0.6 on 2024-06-02 20:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_game_game_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(null=True, related_name='games', to=settings.AUTH_USER_MODEL),
        ),
    ]
